import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/styled-components/registry";
import SessionProvider from "../provider/SessionProvider";
import { auth } from "../lib/next-auth/auth";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await auth();

  return (
    <html lang="ja">
      <StyledComponentsRegistry>
        <body>
          <SessionProvider session={session}>
            <Header session={session} />
            {children}
          </SessionProvider>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
};

export default RootLayout;
